"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { getSupabaseBrowserClient } from "@/lib/db/supabase-browser";

type Metrics=Record<string,number>;
export default function AdminPage(){
 const supabase=getSupabaseBrowserClient();const[email,setEmail]=useState("");const[token,setToken]=useState<string|null>(null);const[metrics,setMetrics]=useState<Metrics|null>(null);const[retention,setRetention]=useState<any>(null);const[dailies,setDailies]=useState<any[]>([]);const[games,setGames]=useState<any[]>([]);const[leagues,setLeagues]=useState<any[]>([]);const[msg,setMsg]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setToken(data.session.access_token);load(data.session.access_token)}});const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{const t=s?.access_token??null;setToken(t);if(t)load(t)});return()=>sub.subscription.unsubscribe()},[]);
 async function get(path:string,t:string){return fetch(path,{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.json().then(j=>({status:r.status,json:j})))}
 async function load(t=token){if(!t)return;const[m,d,g,l]=await Promise.all([get("/api/admin/metrics",t),get("/api/admin/dailies",t),get("/api/admin/games",t),get("/api/admin/leagues",t)]);if(m.status===401){setMsg("Signed in, but this account is not an admin. Add its email to ADMIN_EMAILS in Vercel.");return;}setMetrics(m.json.today??null);setRetention(m.json.retention??null);setDailies(d.json.dailies??[]);setGames(g.json.games??[]);setLeagues(l.json.leagues??[])}
 async function login(){const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${window.location.origin}/admin`}});setMsg(error?error.message:"Check your email for the admin sign-in link.")}
 async function seed(){if(!token)return;const date=new Date().toISOString().slice(0,10);const r=await fetch("/api/admin/seed-daily",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({date})});setMsg(JSON.stringify(await r.json()));load()}
 async function close(date:string){if(!token)return;const r=await fetch("/api/admin/close-daily",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({date,force:true})});setMsg(JSON.stringify(await r.json()));load()}
 async function toggleGame(slug:string,enabled:boolean){if(!token)return;await fetch("/api/admin/games",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({slug,enabled})});load()}
 async function runWeeklySnapshot(){if(!token)return;const r=await fetch("/api/admin/league-weekly-snapshot",{method:"POST",headers:{Authorization:`Bearer ${token}`}});setMsg(JSON.stringify(await r.json()))}
 async function runStreakReminders(){if(!token)return;const r=await fetch("/api/admin/streak-reminders",{method:"POST",headers:{Authorization:`Bearer ${token}`}});setMsg(JSON.stringify(await r.json()))}
 if(!token)return <main style={{minHeight:"100dvh",padding:"2rem",maxWidth:"30rem",margin:"0 auto"}}><Link href="/">← HOME</Link><h1 style={{marginTop:"2rem"}}>ADMIN</h1><p style={{color:"var(--muted)"}}>Supabase Auth protected. No secret URLs.</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" style={{width:"100%",padding:"1rem",margin:"1rem 0",borderRadius:12}}/><button className="big-tap-button" onPointerDown={login}>SIGN IN BY EMAIL</button><p>{msg}</p></main>;
 return <main style={{minHeight:"100dvh",padding:"1.5rem",maxWidth:"62rem",margin:"0 auto",display:"grid",gap:"1.5rem"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h1>THE CUT ADMIN</h1><button className="secondary-link" onPointerDown={()=>supabase.auth.signOut()}>SIGN OUT</button></div>
 <section><h2>TODAY</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:".75rem"}}>{metrics&&Object.entries(metrics).map(([k,v])=><div className="stat-tile" key={k}><span>{k.replace(/([A-Z])/g," $1").toUpperCase()}</span><strong>{v}{k.toLowerCase().includes("rate")?"%":""}</strong></div>)}</div>{retention&&<div style={{display:"flex",gap:".75rem",marginTop:".75rem",flexWrap:"wrap"}}><div className="stat-tile"><span>D1 RETENTION</span><strong>{retention.d1.rate??"—"}%</strong><small>{retention.d1.returned}/{retention.d1.cohort}</small></div><div className="stat-tile"><span>D7 RETENTION</span><strong>{retention.d7.rate??"—"}%</strong><small>{retention.d7.returned}/{retention.d7.cohort}</small></div></div>}</section>
 <section><div style={{display:"flex",gap:".75rem",alignItems:"center"}}><h2 style={{flex:1}}>DAILIES</h2><button className="secondary-link" onPointerDown={seed}>SEED TODAY</button><button className="secondary-link" onPointerDown={()=>load()}>REFRESH</button></div>{msg&&<p style={{color:"var(--muted)",wordBreak:"break-word"}}>{msg}</p>}<div style={{display:"grid",gap:".5rem"}}>{dailies.map(d=><div key={d.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem",padding:".8rem",border:"1px solid rgba(255,255,255,.1)",borderRadius:12}}><span><strong>{d.daily_date}</strong> · {d.status} · v{d.version}</span>{d.status!=="closed"&&<button className="secondary-link" onPointerDown={()=>close(d.daily_date)}>FORCE CLOSE</button>}</div>)}</div></section>
 <section><h2>GAMES</h2><p style={{color:"var(--muted)"}}>Disabled games are omitted from future newly-seeded Dailies. Existing played Dailies are never rewritten.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:".6rem"}}>{games.map(g=><button key={g.id} onPointerDown={()=>toggleGame(g.slug,!g.enabled)} style={{padding:"1rem",borderRadius:12,border:`1px solid ${g.enabled?"rgba(0,229,160,.35)":"rgba(255,90,90,.35)"}`,background:"rgba(255,255,255,.04)",color:"var(--fg)",textAlign:"left"}}><strong>{g.slug.toUpperCase()}</strong><br/><small>{g.category} · {g.enabled?"ENABLED":"DISABLED"}</small></button>)}</div></section>
 <section><h2>LEAGUES</h2><div style={{display:"flex",gap:".75rem",alignItems:"center",marginBottom:".75rem"}}><button className="secondary-link" onPointerDown={runWeeklySnapshot}>RUN WEEKLY SNAPSHOT NOW</button></div><div style={{display:"grid",gap:".5rem"}}>{leagues.length?leagues.map(l=><div key={l.id} style={{padding:".8rem",border:"1px solid rgba(255,255,255,.1)",borderRadius:12}}><strong>{l.name}</strong> · {l.memberCount} members · code {l.invite_code}</div>):<p style={{color:"var(--muted)"}}>No leagues yet.</p>}</div></section>
 <section><h2>PUSH NOTIFICATIONS</h2><p style={{color:"var(--muted)"}}>Sends immediately to any subscribed player with an active streak they haven't played today — ignores the evening-hour window so it's testable any time.</p><button className="secondary-link" onPointerDown={runStreakReminders}>SEND STREAK REMINDERS NOW</button></section>
 </main>
}
