"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { nowMs,RESULT_REVEAL_MS } from "@/lib/microgames/engine/timing";
import { hapticResult } from "@/lib/microgames/engine/haptics";
import { soundGood, soundBad } from "@/lib/microgames/engine/sound";
import { JeopardyTimer } from "@/lib/microgames/engine/JeopardyTimer";
import type { MicrogameConfig,MicrogameInputEvent,MicrogameResult } from "@/lib/microgames/engine/types";
import { computeCountError,computeCountScore,isCountResultPlausible } from "./scorer";
type Phase="showing"|"answering"|"result";interface DotPosition{x:number;y:number}
export function CountGame({config,onFinish}:{config:MicrogameConfig;onFinish:(result:MicrogameResult)=>void}){const showMs=config.difficulty.showMs??900,minCount=config.difficulty.minCount??5,maxCount=config.difficulty.maxCount??12,deadlineMs=config.difficulty.answerDeadlineMs??5000;const[phase,setPhase]=useState<Phase>("showing");const[error,setError]=useState<number|null>(null);const[remainingMs,setRemainingMs]=useState(deadlineMs);const answerStartRef=useRef<number|null>(null);const showTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);const deadlineRef=useRef<ReturnType<typeof setTimeout>|null>(null);const tickRef=useRef<ReturnType<typeof setInterval>|null>(null);const resultTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);const finishedRef=useRef(false);const actualCount=useMemo(()=>config.difficulty.actualCount??Math.floor(minCount+Math.random()*(maxCount-minCount+1)),[config.difficulty.actualCount,minCount,maxCount]);const dots:DotPosition[]=useMemo(()=>Array.from({length:actualCount},()=>({x:.1+Math.random()*.8,y:.1+Math.random()*.8})),[actualCount]);
 useEffect(()=>{showTimerRef.current=setTimeout(()=>{answerStartRef.current=nowMs();setPhase("answering");tickRef.current=setInterval(()=>{if(answerStartRef.current!==null)setRemainingMs(Math.max(0,deadlineMs-(nowMs()-answerStartRef.current)));},50);deadlineRef.current=setTimeout(()=>finishTimeout(),deadlineMs);},showMs);return()=>cleanup();},[]);
 function cleanup(){if(showTimerRef.current)clearTimeout(showTimerRef.current);if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current);if(resultTimerRef.current)clearTimeout(resultTimerRef.current);}
 function complete(events:MicrogameInputEvent[],guess:number|null,timedOut=false){if(finishedRef.current)return;finishedRef.current=true;if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current);const effectiveConfig:MicrogameConfig={...config,difficulty:{...config.difficulty,actualCount,answerDeadlineMs:deadlineMs}};const countError=timedOut?Number.POSITIVE_INFINITY:computeCountError(effectiveConfig,events);const score=computeCountScore(effectiveConfig,events);const plausible=isCountResultPlausible(effectiveConfig,events);const answerTimeMs=events[0]?.clientTimestamp??deadlineMs;const accuracy=timedOut?0:Math.max(0,100*(1-countError/Math.max(actualCount,1)));const performanceScore=timedOut?0:Math.max(0,Math.round(accuracy*8+Math.max(0,200-answerTimeMs/12)));setError(countError);setPhase("result");hapticResult(plausible&&!timedOut&&countError===0); if(plausible&&!timedOut&&countError===0){soundGood();}else{soundBad();}resultTimerRef.current=setTimeout(()=>onFinish({rawScore:score,metricDirection:"lower_is_better",inputEvents:events,clientComputedScore:score,failed:timedOut||!plausible,failureReason:timedOut?"timeout":plausible?undefined:"invalid_guess",feedback:{title:timedOut?"TIME'S UP":undefined,primaryLabel:timedOut?"ACTUAL":"YOUR GUESS",primaryValue:timedOut?String(actualCount):String(guess),targetLabel:"ACTUAL",targetValue:String(actualCount),errorLabel:timedOut?"RESULT":"ERROR",errorValue:timedOut?"NO ANSWER":countError===0?"EXACT":`${countError} ${guess!==null&&guess<actualCount?"SHORT":"OVER"}`,direction:countError===0?"exact":"none",accuracyPct:accuracy,rating:timedOut?"poor":countError===0?"perfect":countError===1?"great":countError===2?"good":"poor",performanceScore,timeMs:answerTimeMs,secondaryStats:[{label:"TIME",value:`${(answerTimeMs/1000).toFixed(2)}s`,tone:answerTimeMs<1200?"good":answerTimeMs<3000?"warn":"bad"},{label:"LIMIT",value:"5.00s",tone:timedOut?"bad":"neutral"}],message:timedOut?"Five seconds. No answer means no score.":countError===0?"Perfect count — speed separated the score.":guess!==null&&guess<actualCount?`You were ${countError} short. Accuracy first, speed second.`:`You were ${countError} over. Accuracy first, speed second.`}}),RESULT_REVEAL_MS);}
 function finishTimeout(){if(finishedRef.current)return;complete([{type:"timeout",clientTimestamp:deadlineMs,data:{}}],null,true)}
 function handleGuess(guess:number){if(phase!=="answering"||finishedRef.current)return;const answerTimeMs=answerStartRef.current===null?deadlineMs:nowMs()-answerStartRef.current;complete([{type:"answer",clientTimestamp:answerTimeMs,data:{guess}}],guess,false)}
 const answerOptions=Array.from({length:maxCount+3},(_,i)=>i+1);
 return <div className="game-stage" style={{position:"fixed",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:"1.25rem",padding:"1.4rem"}}>{phase==="showing"&&<><p className="game-instruction" style={{color:"var(--muted)"}}>COUNT THE FLASH</p><div style={{width:"min(76vw,340px)",height:"min(76vw,340px)",position:"relative"}}>{dots.map((dot,i)=><div key={i} style={{position:"absolute",left:`${dot.x*100}%`,top:`${dot.y*100}%`,width:"13%",aspectRatio:"1",borderRadius:"50%",background:"#ff941a",boxShadow:"0 0 22px rgba(255,148,26,.4)",transform:"translate(-50%,-50%)"}}/>)}</div></>}{phase==="answering"&&<><JeopardyTimer remainingMs={remainingMs} totalMs={deadlineMs} label="ANSWER IN"/><p className="game-instruction" style={{color:"var(--muted)"}}>HOW MANY?</p><div style={{display:"flex",flexWrap:"wrap",gap:".5rem",justifyContent:"center",maxWidth:"22rem"}}>{answerOptions.map(n=><button key={n} onPointerDown={()=>handleGuess(n)} style={{width:"3rem",height:"3rem",borderRadius:"50%",border:"1px solid rgba(255,148,26,.32)",background:"rgba(255,148,26,.07)",color:"var(--fg)",fontFamily:"var(--font-mono)",fontSize:"1rem"}}>{n}</button>)}</div></>}{phase==="result"&&<div className="result-reveal" style={{textAlign:"center"}}><p className="game-number" style={{color:error===0?"var(--survive)":"var(--cut)"}}>{!Number.isFinite(error??Infinity)?"TIME":error===0?"EXACT":`±${error}`}</p><p className="game-instruction" style={{color:"var(--muted)"}}>actual: {actualCount}</p></div>}</div>}
