"use client";
import { useEffect,useRef,useState } from "react";
import { nowMs,RESULT_REVEAL_MS } from "@/lib/microgames/engine/timing";
import { hapticResult } from "@/lib/microgames/engine/haptics";
import { JeopardyTimer } from "@/lib/microgames/engine/JeopardyTimer";
import type { MicrogameConfig,MicrogameInputEvent,MicrogameResult } from "@/lib/microgames/engine/types";
import { computeTraceDeviation,computeTraceScore,isTraceResultPlausible,traceAccuracyPct,traceDurationMs } from "./scorer";
type Phase="playing"|"result";const MIN_SAMPLE_INTERVAL_MS=25;
export function TraceGame({config,onFinish}:{config:MicrogameConfig;onFinish:(result:MicrogameResult)=>void}){const radius=config.difficulty.targetRadius??.3,accuracyThresholdPct=config.difficulty.accuracyThresholdPct??90,timeLimitMs=config.difficulty.timeLimitMs??10_000;const[phase,setPhase]=useState<Phase>("playing");const[drawnPoints,setDrawnPoints]=useState<{x:number;y:number}[]>([]);const[error,setError]=useState<number|null>(null);const[remainingMs,setRemainingMs]=useState(timeLimitMs);const containerRef=useRef<HTMLDivElement>(null),roundStartRef=useRef(nowMs()),isDraggingRef=useRef(false),lastSampleRef=useRef(0),pointsRef=useRef<MicrogameInputEvent[]>([]),resultTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null),deadlineRef=useRef<ReturnType<typeof setTimeout>|null>(null),tickRef=useRef<ReturnType<typeof setInterval>|null>(null),finishedRef=useRef(false);
 useEffect(()=>{roundStartRef.current=nowMs();tickRef.current=setInterval(()=>setRemainingMs(Math.max(0,timeLimitMs-(nowMs()-roundStartRef.current))),50);deadlineRef.current=setTimeout(()=>finish(true),timeLimitMs);return()=>{if(resultTimerRef.current)clearTimeout(resultTimerRef.current);if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current);};},[]);
 function normalizedPoint(clientX:number,clientY:number){if(!containerRef.current)return null;const rect=containerRef.current.getBoundingClientRect();return{x:(clientX-rect.left)/rect.width,y:(clientY-rect.top)/rect.height};}
 function handlePointerDown(e:React.PointerEvent<HTMLDivElement>){if(phase!=="playing"||finishedRef.current)return;isDraggingRef.current=true;pointsRef.current=[];setDrawnPoints([]);recordPoint(e.clientX,e.clientY)}
 function handlePointerMove(e:React.PointerEvent<HTMLDivElement>){if(!isDraggingRef.current||phase!=="playing")return;const now=nowMs();if(now-lastSampleRef.current<MIN_SAMPLE_INTERVAL_MS)return;lastSampleRef.current=now;recordPoint(e.clientX,e.clientY)}
 function recordPoint(clientX:number,clientY:number){const point=normalizedPoint(clientX,clientY);if(!point)return;pointsRef.current.push({type:"point",clientTimestamp:nowMs()-roundStartRef.current,data:{x:point.x,y:point.y}});setDrawnPoints(prev=>[...prev,point])}
 function handlePointerUp(){if(!isDraggingRef.current||phase!=="playing")return;isDraggingRef.current=false;finish(false)}
 function finish(timedOut:boolean){if(finishedRef.current)return;finishedRef.current=true;isDraggingRef.current=false;if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current);const events=pointsRef.current;if(timedOut&&events.length>0){const last=events[events.length-1]!;events[events.length-1]={...last,clientTimestamp:timeLimitMs};}const effectiveConfig:MicrogameConfig={...config,difficulty:{...config.difficulty,accuracyThresholdPct,timeLimitMs}};const deviation=computeTraceDeviation(effectiveConfig,events),score=computeTraceScore(effectiveConfig,events),plausible=isTraceResultPlausible(effectiveConfig,events),traceTimeMs=traceDurationMs(events),accuracyPct=traceAccuracyPct(effectiveConfig,events),thresholdPassed=accuracyPct>=accuracyThresholdPct,speedBonus=thresholdPassed&&Number.isFinite(traceTimeMs)?Math.max(0,250-traceTimeMs/20):0,performanceScore=Math.max(0,Math.min(1000,Math.round(accuracyPct*7.5+speedBonus)));setError(deviation);setPhase("result");hapticResult(plausible&&thresholdPassed&&!timedOut);resultTimerRef.current=setTimeout(()=>onFinish({rawScore:score,metricDirection:"lower_is_better",inputEvents:events,clientComputedScore:score,failed:!plausible,failureReason:!plausible?(timedOut?"timeout_or_trace_too_short":"trace_too_short"):undefined,feedback:{title:timedOut?"TIME’S UP":thresholdPassed?"QUALIFIED":"NOT ACCURATE ENOUGH",primaryLabel:"ACCURACY",primaryValue:`${accuracyPct.toFixed(1)}%`,targetLabel:"THRESHOLD",targetValue:`${accuracyThresholdPct.toFixed(0)}%+`,errorLabel:"TIME",errorValue:Number.isFinite(traceTimeMs)?`${(traceTimeMs/1000).toFixed(2)}s`:"NO TRACE",direction:"none",accuracyPct,rating:deviation<=.02?"perfect":deviation<=.04?"excellent":deviation<=.07?"great":deviation<=.12?"good":deviation<=.2?"close":"poor",performanceScore,timeMs:Number.isFinite(traceTimeMs)?traceTimeMs:timeLimitMs,thresholdPct:accuracyThresholdPct,thresholdPassed,secondaryStats:[{label:"TIME",value:Number.isFinite(traceTimeMs)?`${(traceTimeMs/1000).toFixed(2)}s`:"10.00s",tone:timedOut?"bad":thresholdPassed?"good":"neutral"},{label:"LIMIT",value:"10.00s",tone:timedOut?"bad":"neutral"},{label:"THRESHOLD",value:`${accuracyThresholdPct.toFixed(0)}%`,tone:thresholdPassed?"good":"warn"}],message:timedOut?`Time expired. You reached ${accuracyPct.toFixed(1)}% accuracy; ${accuracyThresholdPct.toFixed(0)}% is required.`:thresholdPassed?"Qualified. Accuracy cleared — now a faster clean trace scores higher.":`Not accurate enough: ${accuracyPct.toFixed(1)}%. Reach ${accuracyThresholdPct.toFixed(0)}% before speed can help.`}}),RESULT_REVEAL_MS)}
 const pathAttr=drawnPoints.map(p=>`${p.x*100},${p.y*100}`).join(" ");
 return <div className="game-stage" style={{position:"fixed",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:"1rem",padding:"1rem"}}><JeopardyTimer remainingMs={remainingMs} totalMs={timeLimitMs} label="TRACE LIMIT"/><p className="game-instruction" style={{color:"var(--muted)"}}>TRACE THE CIRCLE · 90%+ TO SCORE SPEED</p><div ref={containerRef} onPointerDown={handlePointerDown} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} style={{width:"min(72vw,340px)",height:"min(72vw,340px)",position:"relative",touchAction:"none"}}><svg viewBox="0 0 100 100" width="100%" height="100%"><circle cx={50} cy={50} r={radius*100} fill="none" stroke="rgba(255,63,121,.45)" strokeWidth={1.5} strokeDasharray="4 3"/>{drawnPoints.length>1&&<polyline points={pathAttr} fill="none" stroke={phase==="result"?(error!==null&&error<.05?"var(--survive)":"var(--cut)"):"#ff3f79"} strokeWidth={2.3} strokeLinecap="round" strokeLinejoin="round" style={{filter:"drop-shadow(0 0 7px rgba(255,63,121,.45))"}}/>}</svg></div>{phase==="result"&&error!==null&&<div className="result-reveal" style={{textAlign:"center"}}><p className="game-number" style={{color:error<.05?"var(--survive)":"var(--cut)"}}>{Number.isFinite(error)?`${(100-error*100).toFixed(1)}%`:"TIME"}</p><p className="game-instruction" style={{color:"var(--muted)"}}>accuracy</p></div>}</div>}
