"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { nowMs, RESULT_REVEAL_MS } from "@/lib/microgames/engine/timing";
import { hapticResult } from "@/lib/microgames/engine/haptics";
import { JeopardyTimer } from "@/lib/microgames/engine/JeopardyTimer";
import type { MicrogameConfig, MicrogameInputEvent, MicrogameResult } from "@/lib/microgames/engine/types";
import { computeHalfScore, isHalfResultPlausible } from "./scorer";

type Phase = "playing" | "result";
function generateLine(){const length=.35+Math.random()*.4;const start=Math.random()*(1-length);return{start,end:start+length}}

export function HalfGame({config,onFinish}:{config:MicrogameConfig;onFinish:(result:MicrogameResult)=>void}){
 const timeLimitMs=config.difficulty.timeLimitMs??1400;const[phase,setPhase]=useState<Phase>("playing");const[remainingMs,setRemainingMs]=useState(timeLimitMs);const[error,setError]=useState<number|null>(null);const[tapX,setTapX]=useState<number|null>(null);const containerRef=useRef<HTMLDivElement>(null);const startRef=useRef(nowMs());const tickRef=useRef<ReturnType<typeof setInterval>|null>(null);const deadlineRef=useRef<ReturnType<typeof setTimeout>|null>(null);const resultRef=useRef<ReturnType<typeof setTimeout>|null>(null);const finished=useRef(false);
 const line=useMemo(()=>(typeof config.difficulty.lineStartX==="number"&&typeof config.difficulty.lineEndX==="number")?{start:config.difficulty.lineStartX,end:config.difficulty.lineEndX}:generateLine(),[config.difficulty.lineStartX,config.difficulty.lineEndX]);const midpoint=(line.start+line.end)/2;
 useEffect(()=>{startRef.current=nowMs();tickRef.current=setInterval(()=>setRemainingMs(Math.max(0,timeLimitMs-(nowMs()-startRef.current))),40);deadlineRef.current=setTimeout(()=>{if(finished.current)return;finished.current=true;setPhase("result");hapticResult(false);onFinish({rawScore:999999,metricDirection:"lower_is_better",inputEvents:[],clientComputedScore:999999,failed:true,failureReason:"timeout",feedback:{title:"TIME’S UP",primaryLabel:"RESULT",primaryValue:"NO CUT",targetLabel:"TASK",targetValue:"FIND HALF",message:"The line disappeared before you committed. Go faster."}})},timeLimitMs);return()=>{if(tickRef.current)clearInterval(tickRef.current);if(deadlineRef.current)clearTimeout(deadlineRef.current);if(resultRef.current)clearTimeout(resultRef.current)}},[timeLimitMs,onFinish]);
 function tap(e:React.PointerEvent<HTMLDivElement>){if(phase!=="playing"||!containerRef.current||finished.current)return;finished.current=true;if(tickRef.current)clearInterval(tickRef.current);if(deadlineRef.current)clearTimeout(deadlineRef.current);const rect=containerRef.current.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width;const elapsed=nowMs()-startRef.current;const effective={...config,difficulty:{...config.difficulty,lineStartX:line.start,lineEndX:line.end,timeLimitMs}};const events:MicrogameInputEvent[]=[{type:"tap",clientTimestamp:elapsed,data:{x}}];const score=computeHalfScore(effective,events),plausible=isHalfResultPlausible(effective,events);setTapX(x);setError(score);setPhase("result");hapticResult(plausible&&score<.08);const perf=Math.max(0,Math.round(1000-score*4500-Math.max(0,elapsed-250)*.08));resultRef.current=setTimeout(()=>onFinish({rawScore:score,metricDirection:"lower_is_better",inputEvents:events,clientComputedScore:score,failed:!plausible,failureReason:plausible?undefined:"implausible_tap",feedback:{primaryLabel:"YOUR CUT",primaryValue:`${(x*100).toFixed(1)}%`,targetLabel:"TRUE HALF",targetValue:`${(midpoint*100).toFixed(1)}%`,errorLabel:"ERROR",errorValue:`${(score*100).toFixed(1)}% ${x<midpoint?"LEFT":x>midpoint?"RIGHT":"EXACT"}`,direction:x<midpoint?"left":x>midpoint?"right":"exact",accuracyPct:Math.max(0,100-score*100),rating:score<=.005?"perfect":score<=.015?"excellent":score<=.035?"great":score<=.07?"good":score<=.12?"close":"poor",performanceScore:perf,timeMs:elapsed,secondaryStats:[{label:"TIME",value:`${(elapsed/1000).toFixed(2)}s`,tone:elapsed<700?"good":elapsed<1100?"warn":"neutral"}],message:score<=.015?"Razor close. Now do it faster.":x<midpoint?"You cut left of centre.":"You cut right of centre."}}),RESULT_REVEAL_MS)}
 return <div className="game-stage" style={{position:"fixed",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:"1.35rem",padding:"2rem"}}><JeopardyTimer remainingMs={remainingMs} totalMs={timeLimitMs} label="CUT BEFORE ZERO"/><p className="game-instruction" style={{color:"var(--muted)"}}>CUT THE LINE EXACTLY IN HALF</p><div ref={containerRef} onPointerDown={tap} style={{width:"min(85vw,460px)",height:"4rem",position:"relative",cursor:phase==="playing"?"crosshair":"default"}}><svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1={line.start*100} x2={line.end*100} y1={50} y2={50} stroke="var(--fg)" strokeWidth={3} strokeLinecap="round"/>{phase==="result"&&<circle cx={midpoint*100} cy={50} r={2.2} fill="var(--survive)"/>}{phase==="result"&&tapX!==null&&<circle cx={tapX*100} cy={50} r={2.2} fill="var(--cut)"/>}</svg></div>{phase==="result"&&error!==null&&<div className="result-reveal" style={{textAlign:"center"}}><p className="game-number" style={{color:error<.08?"var(--survive)":"var(--cut)"}}>{(error*100).toFixed(1)}%</p><p className="game-instruction" style={{color:"var(--muted)"}}>off centre</p></div>}</div>
}
