"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { nowMs, RESULT_REVEAL_MS } from "@/lib/microgames/engine/timing";
import { hapticResult } from "@/lib/microgames/engine/haptics";
import { soundGood, soundBad } from "@/lib/microgames/engine/sound";
import { JeopardyTimer } from "@/lib/microgames/engine/JeopardyTimer";
import type { MicrogameConfig, MicrogameInputEvent, MicrogameResult } from "@/lib/microgames/engine/types";
import { computeBiggerScore, isBiggerResultPlausible } from "./scorer";

type Phase="playing"|"result"; type ShapeKind="circle"|"square"|"triangle"; const SHAPE_KINDS:ShapeKind[]=["circle","square","triangle"];
function randomOffset(){return -12+Math.random()*24} function shapeStyle(kind:ShapeKind,sizePx:number):React.CSSProperties{const base:React.CSSProperties={width:sizePx,height:sizePx,background:"var(--fg)",border:"none",cursor:"pointer"};if(kind==="circle")return{...base,borderRadius:"50%"};if(kind==="square")return{...base,borderRadius:"12%"};return{...base,background:"transparent"};}

export function BiggerGame({config,onFinish}:{config:MicrogameConfig;onFinish:(result:MicrogameResult)=>void}){
 const sizeDiffPct=config.difficulty.sizeDifferencePct??.12; const timeLimitMs=config.difficulty.timeLimitMs??500; const [phase,setPhase]=useState<Phase>("playing"); const [remainingMs,setRemainingMs]=useState(timeLimitMs); const [reactionMs,setReactionMs]=useState<number|null>(null); const [wasCorrect,setWasCorrect]=useState(false); const roundStartRef=useRef(nowMs()); const deadlineRef=useRef<ReturnType<typeof setTimeout>|null>(null); const tickRef=useRef<ReturnType<typeof setInterval>|null>(null); const resultTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);
 const biggerSide=useMemo(()=>(config.difficulty.biggerSide===0||config.difficulty.biggerSide===1?config.difficulty.biggerSide:(Math.random()<.5?0:1)) as 0|1,[config.difficulty.biggerSide]); const shapeKind=useMemo(()=>SHAPE_KINDS[Math.floor(config.difficulty.shapeKind??Math.random()*SHAPE_KINDS.length)]??"circle",[config.difficulty.shapeKind]); const jitter=useMemo(()=>[randomOffset(),randomOffset()],[]); const baseSizePx=86; const biggerSizePx=baseSizePx*(1+sizeDiffPct);
 useEffect(()=>{roundStartRef.current=nowMs();tickRef.current=setInterval(()=>setRemainingMs(Math.max(0,timeLimitMs-(nowMs()-roundStartRef.current))),50);deadlineRef.current=setTimeout(()=>{setPhase("result");hapticResult(false);soundBad();onFinish({rawScore:timeLimitMs,metricDirection:"lower_is_better",inputEvents:[],clientComputedScore:timeLimitMs,failed:true,failureReason:"timeout",feedback:{title:"TIME’S UP",primaryLabel:"RESULT",primaryValue:"NO CHOICE",targetLabel:"TASK",targetValue:"PICK THE BIGGER SHAPE",message:"Half a second at full pressure. Trust your eyes and choose."}})},timeLimitMs);return()=>{if(resultTimerRef.current)clearTimeout(resultTimerRef.current);if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current)}},[onFinish]);
 function handleTap(side:0|1){if(phase!=="playing")return;if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current); const effectiveConfig:MicrogameConfig={...config,difficulty:{...config.difficulty,biggerSide}}; const elapsedMs=nowMs()-roundStartRef.current; const events:MicrogameInputEvent[]=[{type:"tap",clientTimestamp:elapsedMs,data:{side}}]; const score=computeBiggerScore(effectiveConfig,events); const plausible=isBiggerResultPlausible(effectiveConfig,events); setReactionMs(score);setWasCorrect(plausible);setPhase("result");hapticResult(plausible); if(plausible){soundGood();}else{soundBad();}
 resultTimerRef.current=setTimeout(()=>onFinish({rawScore:score,metricDirection:"lower_is_better",inputEvents:events,clientComputedScore:score,failed:!plausible,failureReason:plausible?undefined:"wrong_shape",feedback:{primaryLabel:plausible?"TIME":"RESULT",primaryValue:plausible?`${Math.round(score)}ms`:"WRONG",targetLabel:"PICK",targetValue:"BIGGER SHAPE",errorLabel:plausible?"CHOICE":"MISS",errorValue:plausible?"CORRECT":"WRONG SHAPE",direction:plausible?"correct":"wrong",accuracyPct:plausible?100:0,rating:plausible&&score<300?"excellent":plausible&&score<600?"great":plausible?"good":"poor",performanceScore:plausible?Math.max(0,Math.round(1000-Math.max(0,score-180)*.7)):0,timeMs:plausible?score:undefined,secondaryStats:plausible?[{label:"TIME",value:`${Math.round(score)}ms`,tone:score<350?"good":score<650?"warn":"neutral"},{label:"CHOICE",value:"CORRECT",tone:"good"}]:[{label:"CHOICE",value:"WRONG",tone:"bad"}],message:plausible?"Correct. Faster decisions climb the board.":"Wrong shape — accuracy comes before speed."}}),RESULT_REVEAL_MS);}
 function renderShape(side:0|1){const size=side===biggerSide?biggerSizePx:baseSizePx; const common={...shapeStyle(shapeKind,size),transform:`translateY(${jitter[side]??0}px) scale(${phase==="playing"?1:wasCorrect&&side===biggerSide?1.08:.95})`,transition:"transform .18s ease, opacity .18s ease",opacity:phase==="result"&&!wasCorrect&&side!==biggerSide?.45:1}; if(shapeKind!=="triangle")return <button aria-label={`shape ${side+1}`} onPointerDown={()=>handleTap(side)} style={common}/>; return <button aria-label={`shape ${side+1}`} onPointerDown={()=>handleTap(side)} style={{...common,width:size,height:size,clipPath:"polygon(50% 0%, 0% 100%, 100% 100%)",background:"var(--fg)"}}/>;}
 return <div className="game-stage" style={{position:"fixed",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:"2rem",padding:"2rem"}}><JeopardyTimer remainingMs={remainingMs} totalMs={timeLimitMs} label="CHOOSE"/><p className="game-instruction" style={{color:"var(--muted)"}}>WHICH SHAPE IS BIGGER?</p><div style={{display:"flex",alignItems:"center",justifyContent:"space-around",width:"min(84vw,420px)",height:"12rem"}}>{renderShape(0)}{renderShape(1)}</div>{phase==="result"&&reactionMs!==null&&<div className="result-reveal" style={{textAlign:"center"}}><p className="game-number" style={{color:wasCorrect?"var(--survive)":"var(--cut)"}}>{wasCorrect?`${Math.round(reactionMs)}ms`:"MISS"}</p><p className="game-instruction" style={{color:"var(--muted)"}}>{wasCorrect?"correct + timed":"wrong shape"}</p></div>}</div>;
}
