"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { nowMs, RESULT_REVEAL_MS } from "@/lib/microgames/engine/timing";
import { hapticResult } from "@/lib/microgames/engine/haptics";
import { soundGood, soundBad } from "@/lib/microgames/engine/sound";
import { JeopardyTimer } from "@/lib/microgames/engine/JeopardyTimer";
import type { MicrogameConfig, MicrogameInputEvent, MicrogameResult } from "@/lib/microgames/engine/types";
import { computeCentreScore, isCentreResultPlausible, polygonCentroid, type Point } from "./scorer";

function generatePolygon(pointCount: number): Point[] { const points:Point[]=[]; const baseRadius=.32; for(let i=0;i<pointCount;i++){const angle=(i/pointCount)*Math.PI*2+Math.random()*.3; const radius=baseRadius*(.55+Math.random()*.9); points.push({x:.5+Math.cos(angle)*radius,y:.5+Math.sin(angle)*radius});} return points; }
type Phase = "playing" | "result";

export function CentreGame({ config, onFinish }: { config:MicrogameConfig; onFinish:(result:MicrogameResult)=>void }) {
  const [phase,setPhase]=useState<Phase>("playing"); const timeLimitMs=config.difficulty.timeLimitMs??3000; const [remainingMs,setRemainingMs]=useState(timeLimitMs); const [distance,setDistance]=useState<number|null>(null); const [tapPoint,setTapPoint]=useState<Point|null>(null);
  const containerRef=useRef<HTMLDivElement>(null); const roundStartRef=useRef(nowMs()); const resultTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null); const deadlineRef=useRef<ReturnType<typeof setTimeout>|null>(null); const tickRef=useRef<ReturnType<typeof setInterval>|null>(null);
  const pointCount=Math.round(config.difficulty.pointCount??6); const points=useMemo(()=>{ const configured=Array.from({length:pointCount},(_,i)=>({x:config.difficulty[`p${i}x`],y:config.difficulty[`p${i}y`]})); return configured.every(p=>typeof p.x==="number"&&typeof p.y==="number")?configured as Point[]:generatePolygon(pointCount); },[pointCount,config.difficulty]); const truthCentroid=useMemo(()=>polygonCentroid(points),[points]);
  useEffect(()=>{ roundStartRef.current=nowMs(); tickRef.current=setInterval(()=>setRemainingMs(Math.max(0,timeLimitMs-(nowMs()-roundStartRef.current))),50); deadlineRef.current=setTimeout(()=>{ setPhase("result"); hapticResult(false); soundBad(); onFinish({rawScore:1,metricDirection:"lower_is_better",inputEvents:[],clientComputedScore:1,failed:true,failureReason:"timeout",feedback:{title:"TIME’S UP",primaryLabel:"RESULT",primaryValue:"NO TAP",targetLabel:"TASK",targetValue:"FIND THE CENTRE",message:"Find the exact centre before the clock runs out."}}); },timeLimitMs); return()=>{if(resultTimerRef.current)clearTimeout(resultTimerRef.current);if(deadlineRef.current)clearTimeout(deadlineRef.current);if(tickRef.current)clearInterval(tickRef.current);};},[onFinish]);

  function handleTap(e:React.PointerEvent<HTMLDivElement>){ if(phase!=="playing"||!containerRef.current)return; const rect=containerRef.current.getBoundingClientRect(); const x=(e.clientX-rect.left)/rect.width; const y=(e.clientY-rect.top)/rect.height; const elapsedMs=nowMs()-roundStartRef.current;
    if(deadlineRef.current)clearTimeout(deadlineRef.current); if(tickRef.current)clearInterval(tickRef.current);
    const effectiveConfig:MicrogameConfig={...config,difficulty:{...config.difficulty,...Object.fromEntries(points.flatMap((p,i)=>[[`p${i}x`,p.x],[`p${i}y`,p.y]]))}}; const events:MicrogameInputEvent[]=[{type:"tap",clientTimestamp:elapsedMs,data:{x,y}}]; const score=computeCentreScore(effectiveConfig,events); const plausible=isCentreResultPlausible(effectiveConfig,events); const performanceScore=Math.max(0,Math.round(1000-score*3800-Math.max(0,elapsedMs-250)*.08));
    setTapPoint({x,y});setDistance(score);setPhase("result");hapticResult(plausible&&score<.08); if(plausible&&score<.08){soundGood();}else{soundBad();}
    resultTimerRef.current=setTimeout(()=>onFinish({rawScore:score,metricDirection:"lower_is_better",inputEvents:events,clientComputedScore:score,failed:!plausible,failureReason:plausible?undefined:"implausible_tap",feedback:{primaryLabel:"DISTANCE FROM CENTRE",primaryValue:`${(score*100).toFixed(1)}%`,targetLabel:"TARGET",targetValue:"TRUE CENTRE",errorLabel:"OFFSET",errorValue:`${(score*100).toFixed(1)}%`,direction:"none",accuracyPct:Math.max(0,100-score*100),rating:score<=.01?"perfect":score<=.03?"excellent":score<=.06?"great":score<=.10?"good":score<=.18?"close":"poor",performanceScore,timeMs:elapsedMs,secondaryStats:[{label:"TIME",value:`${(elapsedMs/1000).toFixed(2)}s`,tone:elapsedMs<900?"good":elapsedMs<1600?"warn":"neutral"}],message:score<=.03?"Almost dead centre — now make it instant.":"Green is the true centre. Tighten the gap next run."}}),RESULT_REVEAL_MS);
  }
  const polygonAttr=points.map(p=>`${p.x*100},${p.y*100}`).join(" ");
  return <div className="game-stage" style={{position:"fixed",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:"1.5rem"}}><JeopardyTimer remainingMs={remainingMs} totalMs={timeLimitMs} label="FIND THE CENTRE"/><p className="game-instruction" style={{color:"var(--muted)"}}>TAP THE EXACT CENTRE OF THE SHAPE</p><div ref={containerRef} onPointerDown={handleTap} style={{width:"min(80vw,420px)",height:"min(80vw,420px)",position:"relative",cursor:phase==="playing"?"crosshair":"default"}}><svg viewBox="0 0 100 100" width="100%" height="100%"><polygon points={polygonAttr} fill="var(--fg)" opacity={.92}/>{phase==="result"&&<circle cx={truthCentroid.x*100} cy={truthCentroid.y*100} r={1.4} fill="var(--survive)"/>}{phase==="result"&&tapPoint&&<circle cx={tapPoint.x*100} cy={tapPoint.y*100} r={1.4} fill="var(--cut)"/>}</svg></div>{phase==="result"&&distance!==null&&<div className="result-reveal" style={{textAlign:"center"}}><p className="game-number" style={{color:distance<.08?"var(--survive)":"var(--cut)"}}>{(distance*100).toFixed(1)}%</p><p className="game-instruction" style={{color:"var(--muted)"}}>off core</p></div>}</div>;
}
